# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Sets user-defined palette
palette = "catppuccin_mocha"
command_timeout = 2000

format = """
[](blue)\
$os\
$shell\
$cmd_duration\
[](blue)\
$directory\
$git_branch\
$git_commit\
$git_status\
$python\
$line_break\
$username\
$character\
"""

[os]
disabled = false
style = 'bg:blue fg:base'
format = '[$symbol ]($style)'

[os.symbols]
Arch = '󰣇'
Windows = ''
openSUSE = ' '

[shell]
disabled = false
style = 'bg:blue fg:base'
format = '[$indicator ]($style)'
fish_indicator = '󰈺'
bash_indicator = '󱆃'
zsh_indicator = 'z'
powershell_indicator = '󰨊'
cmd_indicator = ''

[username]
disabled = false
style_root = 'maroon'
style_user = 'blue'
format = '[󰢏 ]($style)'

[character]
success_symbol = "[󰧚 ](green)"
error_symbol = "[󰧚 ](red)"
vimcmd_symbol = "[󰧚 ](blue)"
vimcmd_replace_one_symbol = "[󰧚 ](mauve)"
vimcmd_replace_symbol = "[󰧚 ](teal)"
vimcmd_visual_symbol = "[󰧚 ](yellow)"

[directory]
truncation_length = 3
truncation_symbol = '…'
fish_style_pwd_dir_length = 1
use_os_path_sep = false
style = "bold mauve"
#repo_root_style = "bold bg:lavender fg:red_text"
format = '[ $path ]($style)'
#repo_root_format = '[  $path ]($repo_root_style)'

#[directory.substitutions]
#"Documents" = "󰈙 "
#"Downloads" = " "
#"Music" = " "
#"Pictures" = " "
#"~/Projects/Source" = '󰅱 '
#"~/Projects/Testing" = '󰙨 '
#"~/Projects/Binaries" = ' '
#"~/Tools" = ' '
#"~/OneDrive - Rockwell Automation, Inc" = '󰏊 '

[git_branch]
style = "peach"
format = "[ $symbol$branch]($style)"

[git_commit]
style = "peach"
tag_disabled = false
tag_symbol = '  '
format = "[ $hash$tag ]($style)"

[git_status]
style = "peach"
conflicted = '[ ](fg:red)'
ahead = '󰜷${count} '
behind = '󰜮${count} '
diverged = '󰜷${ahead_count} 󰜮${behind_count} '
up_to_date = ''
untracked = ' '
stashed = ''
modified = ' '
staged = '󰗖 '
renamed = ' '
deleted = ' '
ignore_submodules = true
format = "[ $all_status$ahead_behind ]($style)"

[python]
style = "green"
symbol = '󰌠 '
version_format = 'v${major}.${minor}'
format = '[${symbol}(${version} )(\($virtualenv\))]($style)'

[cmake]
style = "bg:mauve fg:base"
symbol = ' '
version_format = 'v${major}.${minor}'
format = '[ $symbol($version )]($style)'
detect_files = ['CMakeLists.txt', 'CmakeLists.txt', 'Cmakelists.txt', 'cmakelists.txt', 'CMakeCache.txt']

[memory_usage]
disabled = false
threshold = 0
symbol = '󰍛 '
style = "mauve"
format = '[ $symbol$ram_pct ]($style)'

# [time]
# disabled = false
# time_format = '%I:%M %p'
# style = "bg:blue fg:base"
# format = '[ $time ]($style)'

[cmd_duration]
disabled = false
min_time = 1000
# show_milliseconds = true
style = "bg:blue fg:base"
format = '[ $duration ]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
dark_rosewater = "#a5908c"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
dark_pink = "#b582a7"
mauve = "#cba6f7"
dark_mauve = "#8b66b7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
dark_yellow = "#99824f"
green = "#a6e3a1"
dark_green = "#66a361"
teal = "#94e2d5"
dark_teal = "#54a295"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
dark_blue = "#499cac"
lavender = "#b4befe"
dark_lavender = "#747ebe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
red_text = "#932b48"

